name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # تحديث للإصدار الأخير 2025

      - name: Build with Buildozer
        uses: kivy/buildozer-action@master # استخدام النسخة الرئيسية المباشرة
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4 # حل مشكلة الـ Deprecation v3
        with:
          name: AlDhahra-APK
          path: bin/*.apk
